train:
  batch_size: 128
  seed: 2021
  epochs: 10
  shuffle: true
  resume_train: false
  eval: false
  true_dir: data/qm9_processed/val_data_5k.pkl
  gen_dir: log/test/qm9_default/ConfGF_s0e200epoch284min_sig0.000.pkl
  num_data: 200000
  num_workers: 0
  gpus:
    - 0
    - null
    - null
    - null
  anneal_power: 2.0
  save: true
  save_path: checkpoints/discriminator
  resume_checkpoint: null
  resume_epoch: null
  log_interval: 400
  optimizer:
    type: Adam
    lr: 0.001
    weight_decay: 0.000
    dropout: 0.0
  scheduler:
    type: plateau
    factor: 0.6
    # factor: 0.95
    patience: 10
    min_lr: 1e-4
  ema: true
  ema_decay: 0.999


test:
  init_checkpoint: checkpoints/discriminator/sde/qm9_dg_default2021
  output_path: log/dg/qm9
  epoch: 9
  gen_dir: log/test/qm9_default/ConfGF_s0e200epoch284min_sig0.000.pkl
  gen:
    dg_step_size: 3.0
    dg_num_steps: 1000  
    steps_d: 100
    step_lr_d: 0.000002
    steps_pos: 100
    step_lr_pos: 0.0000024
    clip: 1000
    min_sigma: 0.0
    verbose: 1


data:
  base_path: data
  dataset: qm9
  train_set: train_data_40k.pkl
  val_set: val_data_5k.pkl
  test_set: test_data_200.pkl


model:
  name: qm9_dg_default
  hidden_dim: 256
  num_convs: 4
  sigma_begin: 10
  sigma_end: 0.01
  num_noise_level: 50
  order: 3
  mlp_act: relu
  gnn_act: relu
  cutoff: 10.0
  short_cut: true
  concat_hidden: false   
  noise_type: symmetry
  edge_encoder: mlp

scheme:
  framework: 'sde'
  time_continuous: true

